version: '3'
services:
  db:
    image: mysql:5.6
    container_name: mysql_host
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: 'America/Los_Angeles'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --innodb-use-native-aio=0
    volumes:
    - ./docker/db/data:/var/lib/mysql
    - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
    - ./docker/db/sql:/docker-entrypoint-initdb.d
    ports:
    - 3306:3306
    restart: always
  api:
    build:
      context: ./
      dockerfile: ./docker/api/Dockerfile
    deploy:
      resources:
        limits:
          cpus: "1"
    command: yarn start:dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    tty: true
    restart: always
    depends_on:
      - db
